language: java
jdk:
  - openjdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - lolicol1@qq.com
    on_failure: always